remote_theme: sujaykundu777/devlopr-jekyll  # Don't touch ( required for this theme)

# Edit your preferences below 
title: Adrian
subtitle: Developer
description: >- # this means to ignore newlines until "baseurl:"
  John Doe uses devlopr-jekyll - a Jekyll Theme Built For Developers

url: "https://adrianEVI.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Blog
      url: /blog
    - text: About Me
      url: /about
    - text: Contact Me
      url : /contact
    - text: Sample Page
      url: /sample-page

# Edit these details 

author_logo: sf.png
author: Adrian E. Vazquez I.
author_bio:  hola
author_email: "a.vazquezicedo@gmail.com"
author_location: México
author_website_url: "https://adrianEVI.github.io"

author_work_experiences: 
            - company_name: Google
              #company_logo: google.png
              #company_url: https://google.com
              designation: Software Engineer
              description: Worked on various Google Products
              visibility: false
            - company_name: Microsoft
              #company_logo: microsoft.png
              #company_url: https://microsoft.com
              designation: Azure Developer
              description: Worked on various Azure Cloud Products
              visibility: false

author_education_details:
              - college_logo: unison.png
                college_name: Universidad de Sonora
                #college_url: https://mit.org
                college_degree: Ciencias de la compútacion
                description: Grado universitario
                visibility: true
              - college_logo: ulpgc.jpg
                college_name: Universidad de Las Palmas de Gran Canaria
                #college_url: https://mit.org
                college_degree: Ingenieria informatica
                description: Grado universitario
                visibility: true

author_project_details:
              - #project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                #project_url: https://gamershub.in
                visibility: false
              - #project_thumbnail: programmingebooks.png
                project_title: Programming Ebooks
                project_description: A Platform to easily find and read programming books
                #project_url: https://programmingebooks.com
                visibility: false

# social links
twitter_username: 
github_username:  adrianEVI
facebook_username: 
linkedin_username:
behance_username: 
instagram_username: 
medium_username: 
telegram_username: 
dribbble_username:
flickr_username: 

#for comments using disqus
disqus_shortname: sujay-kundu  

# wakatime username
wakatime_username: 

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
  # - jekyll-archives

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


